Updated the URDF file for the Aloha wx250s
Interbotix/interbotix_ros_manipulators pull request #216
Opened 2024-09-04 20:05 UTC by Shiming-Liang

A new link handle_link and a new joint gripper_handle_link are added. The inertia values of the wrist and the gripper are updated.

2024-09-04 20:38 UTC, lukeschmitt-tr requested changes

2024-09-04 20:38 UTC, lukeschmitt-tr commented on .gitignore
Revert changes to this file

2024-09-04 23:08 UTC, Shiming-Liang commented
The first commit now doesn't change the .gitignore file.
The second commit updates inertia values for the upper arm, upper forearm, and lower forearm.

2024-09-05 14:44 UTC, lukeschmitt-tr approved these changes

2024-09-23 19:51 UTC, closed without merging